# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language

en:
  languageCode: en-us
  disabled: false
  weight: 2
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  menu:
    main:
      -name: English
      -weight: 2

# Uncomment the lines below to configure your website in a second language.

ko:
  languageCode: ko-kr
  disabled: false
  weight: 1
  contentDir: content/ko
  menu:
    main:
      - name: korean
      - weight: 1
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
