# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Introduction
    url: /introduction/
    weight: 10
  - name: About
    url: about/
    weight: 20
  - name: Project
    url: /
    identifier: study
    weight: 30
  - name: C#
    parent: study
    url: csharp
    weight: 10
  - name: Unity
    parent: study
    url: unitystudy
    weight: 20
  - name: Inform
    url: /inform/동아리입부
    weight: 40
  - name: Contact
    url: contact/
    weight: 50